ALTER TABLE "sales_leads"
  ADD COLUMN "entityType" TEXT NOT NULL DEFAULT 'COMPANY',
  ADD COLUMN "location" TEXT,
  ADD COLUMN "registrationId" TEXT,
  ADD COLUMN "sourceData" JSONB,
  ADD COLUMN "countryCode" TEXT,
  ADD COLUMN "countryConfidence" DOUBLE PRECISION,
  ADD COLUMN "countryDetectionSource" TEXT,
  ADD COLUMN "primaryLanguage" TEXT,
  ADD COLUMN "detectedLanguages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "languageConfidence" DOUBLE PRECISION,
  ADD COLUMN "languageDetectionSource" TEXT,
  ADD COLUMN "outreachLanguage" TEXT,
  ADD COLUMN "outreachLanguageReason" TEXT,
  ADD COLUMN "outreachLanguageConfidence" DOUBLE PRECISION,
  ADD COLUMN "draftPromptVersion" TEXT,
  ADD COLUMN "draftModel" TEXT,
  ADD COLUMN "draftPersonalizationFact" TEXT,
  ADD COLUMN "draftGenerationConfidence" DOUBLE PRECISION,
  ADD COLUMN "draftInsufficientPersonalizationData" BOOLEAN,
  ADD COLUMN "draftCreatedAt" TIMESTAMP(3),
  ADD COLUMN "twentyDraftNoteId" TEXT;
