packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true

overrides:
  '@jridgewell/sourcemap-codec': 1.5.5

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
