#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNTIME_DIR="$ROOT_DIR/deploy/runtime"

required() {
  local name="$1"

  if [[ -z "${!name:-}" ]]; then
    echo "Missing required deployment value: $name" >&2
    exit 1
  fi
}

write_env() {
  local path="$1"
  shift
  : >"$path"

  while (($#)); do
    local key="$1"
    local value="$2"
    local escaped

    if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
      echo "$key must be a single-line value" >&2
      exit 1
    fi

    escaped="${value//\\/\\\\}"
    escaped="${escaped//\'/\\\'}"
    escaped="${escaped//\$/\$\$}"
    printf "%s='%s'\n" "$key" "$escaped" >>"$path"
    shift 2
  done
}

for name in \
  POSTGRES_DB \
  POSTGRES_USER \
  POSTGRES_PASSWORD \
  WATCHER_DATABASE_URL \
  STOCKS_TELEGRAM_TOKEN \
  PUBLICATIONS_TELEGRAM_TOKEN \
  TELEGRAM_ALLOWED_USER_IDS \
  OLLAMA_URL \
  OLLAMA_MODEL \
  SEC_USER_AGENT; do
  required "$name"
done

umask 077
rm -rf "$RUNTIME_DIR"
install -d -m 700 "$RUNTIME_DIR"

write_env "$RUNTIME_DIR/compose.env" \
  COMPOSE_PROJECT_NAME "${COMPOSE_PROJECT_NAME:-watcher}"

write_env "$RUNTIME_DIR/postgres.env" \
  POSTGRES_DB "$POSTGRES_DB" \
  POSTGRES_USER "$POSTGRES_USER" \
  POSTGRES_PASSWORD "$POSTGRES_PASSWORD"

write_env "$RUNTIME_DIR/migrate.env" \
  DATABASE_URL "$WATCHER_DATABASE_URL"

write_env "$RUNTIME_DIR/stocks-bot.env" \
  DATABASE_URL "$WATCHER_DATABASE_URL" \
  STOCKS_TELEGRAM_TOKEN "$STOCKS_TELEGRAM_TOKEN" \
  TELEGRAM_ALLOWED_USER_IDS "$TELEGRAM_ALLOWED_USER_IDS" \
  OLLAMA_URL "$OLLAMA_URL" \
  OLLAMA_MODEL "$OLLAMA_MODEL" \
  OLLAMA_KEEP_ALIVE "${OLLAMA_KEEP_ALIVE:-5m}" \
  OLLAMA_MAX_ITEMS_PER_RUN "${OLLAMA_MAX_ITEMS_PER_RUN:-0}" \
  OLLAMA_NUM_CTX "${OLLAMA_NUM_CTX:-4096}" \
  OLLAMA_NUM_PREDICT "${OLLAMA_NUM_PREDICT:-768}" \
  OLLAMA_FULL_ANALYSIS_NUM_PREDICT "${OLLAMA_FULL_ANALYSIS_NUM_PREDICT:-1536}" \
  OLLAMA_RETRIES "${OLLAMA_RETRIES:-1}" \
  OLLAMA_THINK "${OLLAMA_THINK:-false}" \
  OLLAMA_TIMEOUT_MS "${OLLAMA_TIMEOUT_MS:-120000}" \
  STOCK_EVENT_COOLDOWN_MINUTES "${STOCK_EVENT_COOLDOWN_MINUTES:-360}" \
  STOCK_TICKER_ANALYSIS_COOLDOWN_MINUTES "${STOCK_TICKER_ANALYSIS_COOLDOWN_MINUTES:-30}" \
  SOURCE_BACKOFF_BASE_SECONDS "${SOURCE_BACKOFF_BASE_SECONDS:-60}" \
  SOURCE_BACKOFF_MAX_MINUTES "${SOURCE_BACKOFF_MAX_MINUTES:-360}" \
  ALERT_ATTENTION_THRESHOLD "${ALERT_ATTENTION_THRESHOLD:-85}" \
  RECONCILIATION_INTERVAL_MINUTES "${RECONCILIATION_INTERVAL_MINUTES:-1440}" \
  VALIDATION_MIN_SAMPLE_SIZE "${VALIDATION_MIN_SAMPLE_SIZE:-20}" \
  SEC_USER_AGENT "$SEC_USER_AGENT" \
  DEFAULT_TIMEZONE "${DEFAULT_TIMEZONE:-Europe/Prague}" \
  ALPHA_VANTAGE_API_KEY "${ALPHA_VANTAGE_API_KEY:-}" \
  ALPHA_VANTAGE_OPTIONS_ENABLED "${ALPHA_VANTAGE_OPTIONS_ENABLED:-false}" \
  QUIVER_API_TOKEN "${QUIVER_API_TOKEN:-}" \
  PRICE_ANOMALY_THRESHOLD_PERCENT "${PRICE_ANOMALY_THRESHOLD_PERCENT:-4}" \
  GAP_ANOMALY_THRESHOLD_PERCENT "${GAP_ANOMALY_THRESHOLD_PERCENT:-3}" \
  RELATIVE_VOLUME_ANOMALY_THRESHOLD "${RELATIVE_VOLUME_ANOMALY_THRESHOLD:-3}" \
  VOLATILITY_EXPANSION_THRESHOLD "${VOLATILITY_EXPANSION_THRESHOLD:-2}" \
  MARKET_BASELINE_MIN_SNAPSHOTS "${MARKET_BASELINE_MIN_SNAPSHOTS:-5}" \
  OPTIONS_VOLUME_OI_ANOMALY_THRESHOLD "${OPTIONS_VOLUME_OI_ANOMALY_THRESHOLD:-2}" \
  OPTIONS_VOLUME_BASELINE_MULTIPLIER "${OPTIONS_VOLUME_BASELINE_MULTIPLIER:-3}" \
  OPTIONS_BASELINE_MIN_SNAPSHOTS "${OPTIONS_BASELINE_MIN_SNAPSHOTS:-3}" \
  INSTITUTIONAL_CHANGE_THRESHOLD_PERCENT "${INSTITUTIONAL_CHANGE_THRESHOLD_PERCENT:-5}" \
  SHORT_INTEREST_CHANGE_THRESHOLD_PERCENT "${SHORT_INTEREST_CHANGE_THRESHOLD_PERCENT:-10}" \
  SHORT_INTEREST_DAYS_TO_COVER_THRESHOLD "${SHORT_INTEREST_DAYS_TO_COVER_THRESHOLD:-5}" \
  DISCOVERY_MARKET_DATA_ENTITLEMENT "${DISCOVERY_MARKET_DATA_ENTITLEMENT:-EOD}" \
  DISCOVERY_SCAN_INTERVAL_MINUTES "${DISCOVERY_SCAN_INTERVAL_MINUTES:-1440}" \
  DISCOVERY_MOVE_THRESHOLD_PERCENT "${DISCOVERY_MOVE_THRESHOLD_PERCENT:-4}" \
  DISCOVERY_MIN_PRICE "${DISCOVERY_MIN_PRICE:-2}" \
  DISCOVERY_MIN_VOLUME "${DISCOVERY_MIN_VOLUME:-100000}" \
  DISCOVERY_MIN_DOLLAR_VOLUME "${DISCOVERY_MIN_DOLLAR_VOLUME:-1000000}" \
  DISCOVERY_MAX_CANDIDATES "${DISCOVERY_MAX_CANDIDATES:-10}" \
  DISCOVERY_SUPPORTED_EXCHANGES "${DISCOVERY_SUPPORTED_EXCHANGES:-Nasdaq,NYSE,NYSE American}" \
  DISCOVERY_EXCLUDE_OTC "${DISCOVERY_EXCLUDE_OTC:-true}" \
  DISCOVERY_INVESTIGATION_MINUTES "${DISCOVERY_INVESTIGATION_MINUTES:-90}" \
  DISCOVERY_HIGH_RESOLUTION_INTERVAL_MINUTES "${DISCOVERY_HIGH_RESOLUTION_INTERVAL_MINUTES:-5}" \
  DISCOVERY_EVENT_MODE_MINUTES "${DISCOVERY_EVENT_MODE_MINUTES:-120}" \
  DISCOVERY_WATCH_DAYS "${DISCOVERY_WATCH_DAYS:-14}" \
  LOG_LEVEL "${LOG_LEVEL:-info}"

write_env "$RUNTIME_DIR/publications-bot.env" \
  DATABASE_URL "$WATCHER_DATABASE_URL" \
  PUBLICATIONS_TELEGRAM_TOKEN "$PUBLICATIONS_TELEGRAM_TOKEN" \
  TELEGRAM_ALLOWED_USER_IDS "$TELEGRAM_ALLOWED_USER_IDS" \
  OLLAMA_URL "$OLLAMA_URL" \
  OLLAMA_MODEL "$OLLAMA_MODEL" \
  OLLAMA_KEEP_ALIVE "${OLLAMA_KEEP_ALIVE:-5m}" \
  OLLAMA_MAX_ITEMS_PER_RUN "${OLLAMA_MAX_ITEMS_PER_RUN:-0}" \
  OLLAMA_NUM_CTX "${OLLAMA_NUM_CTX:-4096}" \
  OLLAMA_NUM_PREDICT "${OLLAMA_NUM_PREDICT:-768}" \
  OLLAMA_RETRIES "${OLLAMA_RETRIES:-1}" \
  OLLAMA_THINK "${OLLAMA_THINK:-false}" \
  OLLAMA_TIMEOUT_MS "${OLLAMA_TIMEOUT_MS:-120000}" \
  SOURCE_BACKOFF_BASE_SECONDS "${SOURCE_BACKOFF_BASE_SECONDS:-60}" \
  SOURCE_BACKOFF_MAX_MINUTES "${SOURCE_BACKOFF_MAX_MINUTES:-360}" \
  DEFAULT_TIMEZONE "${DEFAULT_TIMEZONE:-Europe/Prague}" \
  LOG_LEVEL "${LOG_LEVEL:-info}"

chmod 600 "$RUNTIME_DIR"/*.env
echo "Rendered production environment files in $RUNTIME_DIR"
